eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  server:
     # 关闭保护模式
    enable-self-preservation: false
    # 清理间隔（默认是60 * 1000 毫秒）
    eviction-interval-timer-in-ms: 60000
    # Eureka 拉取服务列表时间（默认：30秒）
    remote-region-registry-fetch-interval: 5
  client:
    # 表示是否注册自身到eureka服务器  
    registerWithEureka: false
    # 是否从eureka上获取注册信息  
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 从 Eureka 服务器端获取注册信息的间隔时间（默认：30秒）
    registry-fetch-interval-seconds: 5



